import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/banner';


export default function Home() {

  const handleOnBannerBtnClick = () => {
    console.log("hi banner button");
  };

  return (
    <>
      <Head>
        <title>Coffee Delight</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.tailwindcss.com"></script>
      </Head>
      <body className="">
      <main className="pl-64 pt-96">
        <Banner/>
      </main>

      <footer className=""> 
      </footer>
      </body>
    </>
  )
}
